Officially enable the v2 workflow, and upload the results to scribe (#704)
Summary:
This PR enables the V2 workflow on the v2.0 branch, and uploads the result to the internal dashboard.

Pull Request resolved: https://github.com/pytorch/benchmark/pull/704

Reviewed By: erichan1

Differential Revision: D33689463

Pulled By: xuzhao9

fbshipit-source-id: 75ad51917d04cff11842a2dad639c73b26d38dca

diff --git a/.github/workflows/v2-nightly.yml b/.github/workflows/v2-nightly.yml
--- a/.github/workflows/v2-nightly.yml
+++ b/.github/workflows/v2-nightly.yml
@@ -28,7 +28,7 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
         with:
-          ref: xz9/v2-testrun
+          ref: v2.0
       - name: Create conda env
         run: |
           conda create -y -q --name "${CONDA_ENV_NAME}" python=${{ env.PYTHON_VER }}
@@ -59,6 +59,50 @@ jobs:
           . activate "${CONDA_ENV_NAME}"
           WORKFLOW_HOME="${HOME}/${{ env.OUTPUT_DIR }}/gh${GITHUB_RUN_ID}"
           bash ./.github/scripts/run.sh "${WORKFLOW_HOME}"
+      - name: Generate the bisection config
+        run: |
+          set -x
+          . activate "${CONDA_ENV_NAME}"
+          WORKFLOW_HOME="${HOME}/${{ env.OUTPUT_DIR }}/gh${GITHUB_RUN_ID}"
+          mkdir -p benchmark-output/
+          # Update the self-hosted pytorch version
+          pushd "${HOME}/pytorch"
+          git fetch origin
+          popd
+          pip install gitpython pyyaml dataclasses argparse
+          # Compare the result from yesterday and report any perf signals
+          python ./.github/scripts/generate-abtest-config.py \
+                 --pytorch-dir "${HOME}/pytorch" \
+                 --github-issue "${WORKFLOW_HOME}/gh-issue.md" \
+                 --benchmark-dir "${WORKFLOW_HOME}" \
+                 --out "${WORKFLOW_HOME}/bisection.yaml"
+          # Include in the GitHub artifact
+          if [ -f "${WORKFLOW_HOME}/gh-issue.md" ]; then
+            cp "${WORKFLOW_HOME}/bisection.yaml" ./benchmark-output/
+            cp "${WORKFLOW_HOME}/gh-issue.md" ./benchmark-output/
+            # Setup the bisection environment
+            BISECTION_HOME="${HOME}/${{ env.BISECTION_ROOT }}/bisection-gh${GITHUB_RUN_ID}"
+            mkdir -p "${BISECTION_HOME}"
+            cp ./benchmark-output/bisection.yaml "${BISECTION_HOME}/config.yaml"
+          fi
+      - name: Dispatch the bisection workflow
+        if: env.TORCHBENCH_PERF_SIGNAL
+        run: |
+          # Get the workflow ID from
+          # https://api.github.com/repos/pytorch/benchmark/actions/workflows
+          curl -u xuzhao9:${{ secrets.TORCHBENCH_ACCESS_TOKEN }} \
+            -X POST \
+            -H "Accept: application/vnd.github.v3+json" \
+            https://api.github.com/repos/pytorch/benchmark/actions/workflows/16176850/dispatches \
+            -d '{"ref": "main", "inputs": {"issue_name": "bisection-gh'"${GITHUB_RUN_ID}"'" } }'
+      - name: Create the github issue
+        if: env.TORCHBENCH_PERF_SIGNAL
+        uses: peter-evans/create-issue-from-file@v3
+        with:
+          title: V2 Performance Signal Detected by TorchBench CI on ${{ env.TORCHBENCH_PERF_SIGNAL }}
+          content-filepath: ./benchmark-output/gh-issue.md
+          labels: |
+            torchbench-perf-report
       - name: Copy artifact and upload to scribe
         run: |
           . activate "${CONDA_ENV_NAME}"
@@ -66,7 +110,19 @@ jobs:
           LATEST_RESULT=$(find ${HOME}/${{ env.OUTPUT_DIR }}/gh${GITHUB_RUN_ID} -name "*.json" | sort -r | head -1)
           echo "Benchmark result file: ${LATEST_RESULT}"
           mkdir -p benchmark-output/
-          cp "${LATEST_RESULT}" ./benchmark-output/benchmark-result-v1-${TODAY}.json
+          cp "${LATEST_RESULT}" ./benchmark-output/benchmark-result-${CONFIG_VER}-${TODAY}.json
+          # Load environment variables
+          CONFIG_DIR=torchbenchmark/score/configs/${CONFIG_VER}
+          CONFIG_ENV=${CONFIG_DIR}/config-${CONFIG_VER}.env
+          # Load environment variables
+          set -a; source "${CONFIG_ENV}"; set +a
+          SCORE_FILE="./benchmark-result-${CONFIG_VER}-score-${TODAY}.json"
+          # Generate score file
+          python compute_score.py --score_version "${CONFIG_VER}" --benchmark_data_file "${LATEST_RESULT}" > "${SCORE_FILE}"
+          # Enable OSS stat uploads
+          wget -O scripts/scribe.py https://github.com/pytorch/pytorch/raw/master/tools/stats/scribe.py || echo "failed to copy oss stat utils"
+          # Upload result to Scribe
+          python scripts/upload_scribe_${CONFIG_VER}.py --pytest_bench_json "${LATEST_RESULT}" --torchbench_score_file "${SCORE_FILE}"
       - name: Upload artifact
         uses: actions/upload-artifact@v2
         with:
